book_database = {
    "books": [
        {"id": 1, "title": "To Kill a Mockingbird", "author": "Harper Lee", "genre": "Drama", "yearPublished": 1960},
        {"id": 2, "title": "1984", "author": "George Orwell", "genre": "Dystopian", "yearPublished": 1949},
        {"id": 3, "title": "The Great Gatsby", "author": "F. Scott Fitzgerald", "genre": "Novel", "yearPublished": 1925},
        {"id": 4, "title": "Pride and Prejudice", "author": "Jane Austen", "genre": "Romance", "yearPublished": 1813},
        {"id": 5, "title": "The Hobbit", "author": "J.R.R. Tolkien", "genre": "Fantasy", "yearPublished": 1937},
        {"id": 6, "title": "Harry Potter and the Sorcerer's Stone", "author": "J.K. Rowling", "genre": "Fantasy", "yearPublished": 1997},
        {"id": 7, "title": "The Catcher in the Rye", "author": "J.D. Salinger", "genre": "Fiction", "yearPublished": 1951},
        {"id": 8, "title": "Fahrenheit 451", "author": "Ray Bradbury", "genre": "Dystopian", "yearPublished": 1953},
        {"id": 9, "title": "Moby Dick", "author": "Herman Melville", "genre": "Adventure", "yearPublished": 1851},
        {"id": 10, "title": "War and Peace", "author": "Leo Tolstoy", "genre": "Historical", "yearPublished": 1869},
        {"id": 11, "title": "Go Set a Watchman", "author": "Harper Lee", "genre": "Drama", "yearPublished": 2015},
        {"id": 12, "title": "Animal Farm", "author": "George Orwell", "genre": "Dystopian", "yearPublished": 1945},
        {"id": 13, "title": "This Side of Paradise", "author": "F. Scott Fitzgerald", "genre": "Novel", "yearPublished": 1920},
        {"id": 14, "title": "Emma", "author": "Jane Austen", "genre": "Romance", "yearPublished": 1815},
        {"id": 15, "title": "The Silmarillion", "author": "J.R.R. Tolkien", "genre": "Fantasy", "yearPublished": 1977},
        {"id": 16, "title": "Harry Potter and the Chamber of Secrets", "author": "J.K. Rowling", "genre": "Fantasy", "yearPublished": 1998},
        {"id": 17, "title": "Nine Stories", "author": "J.D. Salinger", "genre": "Fiction", "yearPublished": 1953},
        {"id": 18, "title": "The Martian Chronicles", "author": "Ray Bradbury", "genre": "Science Fiction", "yearPublished": 1950},
        {"id": 19, "title": "Billy Budd, Sailor", "author": "Herman Melville", "genre": "Adventure", "yearPublished": 1924},
        {"id": 20, "title": "Anna Karenina", "author": "Leo Tolstoy", "genre": "Historical", "yearPublished": 1877},
        {"id": 21, "title": "Sense and Sensibility", "author": "Jane Austen", "genre": "Romance", "yearPublished": 1811},
        {"id": 22, "title": "Homage to Catalonia", "author": "George Orwell", "genre": "Non-Fiction", "yearPublished": 1938},
        {"id": 23, "title": "The Beautiful and Damned", "author": "F. Scott Fitzgerald", "genre": "Novel", "yearPublished": 1922},
        {"id": 24, "title": "Unfinished Tales", "author": "J.R.R. Tolkien", "genre": "Fantasy", "yearPublished": 1980},
        {"id": 25, "title": "Harry Potter and the Prisoner of Azkaban", "author": "J.K. Rowling", "genre": "Fantasy", "yearPublished": 1999}
    ],
}